apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-httpd-index-configmap
data:
  index.html: |
    <html>
    <h1>Hello from SRE1 - {{ .Values.welcomeMessage }}</h1>
    </br>
    <h1>Hi! This is a configmap Index file </h1>
    </html>
