apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-httpd-jtest
  labels:
    epfl.ch/visibility: public
spec:
  host: {{ .Release.Name }}-hello-from-sre1.epfl.ch
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Release.Name }}-httpd-jtest-service 
