apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-httpd-jtest-service
spec:
  selector:
    app: httpd-jtest
  ports:
    - name: httpd-ports
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
